[package]
name = "identicon_image_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.88"
